### ISSUE TITLE
can't get infer_model.py started

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml-model-enrichment#3]
I have been able to infer models from TSV in the past, but I have no idea what has happened since then.

I pulled main before running this, and the requirement for `biolinkml` was replaced with `linkml`

```
(venv) MAM@MAM-M74 linkml-model-enrichment % ./linkml_model_enrichment/infer_model.py --help
Traceback (most recent call last):
  File "./linkml_model_enrichment/infer_model.py", line 19, in <module>
    from linkml_model.meta import SchemaDefinition
  File "/Users/MAM/Documents/gitrepos/linkml-model-enrichment/venv/lib/python3.8/site-packages/linkml_model/__init__.py", line 5, in <module>
    from linkml_model.meta import ElementName , SchemaDefinitionName , TypeDefinitionName , SubsetDefinitionName , DefinitionName , \
  File "/Users/MAM/Documents/gitrepos/linkml-model-enrichment/venv/lib/python3.8/site-packages/linkml_model/meta.py", line 1068, in <module>
    class PvFormulaOptions(EnumDefinitionImpl):
  File "/Users/MAM/Documents/gitrepos/linkml-model-enrichment/venv/lib/python3.8/site-packages/linkml_model/meta.py", line 1072, in PvFormulaOptions
    CODE = PermissibleValue(text="CODE",
  File "<string>", line 22, in __init__
  File "/Users/MAM/Documents/gitrepos/linkml-model-enrichment/venv/lib/python3.8/site-packages/linkml_model/meta.py", line 990, in __post_init__
    self._normalize_inlined_slot(slot_name="alt_descriptions", slot_type=AltDescription, key_name="source", inlined_as_list=None, keyed=True)
  File "/Users/MAM/Documents/gitrepos/linkml-model-enrichment/venv/lib/python3.8/site-packages/linkml/utils/yamlutils.py", line 107, in _normalize_inlined_slot
    raise ValueError(f"Slot: {slot_name} - unrecognized element: {raw_slot_entry}")
ValueError: Slot: alt_descriptions - unrecognized element: JsonObj()
```

**Comment by cmungall** [comment]
dupe with https://github.com/linkml/linkml/issues/197
